//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBascoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barang
    {
        public string BarangId { get; set; }
        public string MerkBarang { get; set; }
        public string JenisBarang { get; set; }
        public string Harga { get; set; }
        public string Supplier { get; set; }
        public string Stok { get; set; }
    }
}
