//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBascoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karyawan
    {
        public string IdKaryawan { get; set; }
        public string NamaKaryawan { get; set; }
        public string AlamatKaryawan { get; set; }
        public string NoTelpon { get; set; }
        public System.DateTime TglLahir { get; set; }
        public string Bagian { get; set; }
    }
}
