//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBascoo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BascoJayaEntities1 : DbContext
    {
        public BascoJayaEntities1()
            : base("name=BascoJayaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Barang> Barang { get; set; }
        public DbSet<Karyawan> Karyawan { get; set; }
        public DbSet<Pelanggan> Pelanggan { get; set; }
        public DbSet<Pemasaran> Pemasaran { get; set; }
        public DbSet<Pemesanan> Pemesanan { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
    }
}
