//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBascoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelanggan
    {
        public string PelangganID { get; set; }
        public string NamaPelanggan { get; set; }
        public string Alamat { get; set; }
        public string NoTelpon { get; set; }
        public string NegaraAsal { get; set; }
        public string Email { get; set; }
    }
}
