//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBascoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pemesanan
    {
        public string PemesananID { get; set; }
        public string PelangganID { get; set; }
        public string NamaPelanggan { get; set; }
        public string JenisPesanan { get; set; }
        public int JumlahPesanan { get; set; }
        public System.DateTime TglPemesanan { get; set; }
        public string NamaSupplier { get; set; }
        public string StatusPemesanan { get; set; }
    }
}
