//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVBascoo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public string SupplierID { get; set; }
        public string NamaSupplier { get; set; }
        public string AlamatSupplier { get; set; }
        public string NoTelpon { get; set; }
        public string Kota { get; set; }
        public string JenisBarang { get; set; }
    }
}
